# Database Configuration
database:
  meilisearch:
    host: localhost
    port: 7700
    db_path: "/home/arpit/.config/meilisearch/db"
    index_name: audio_metadata
    index_primary_key: file_name_hash
    startup_args:
      - --no-analytics

# Audio Configuration
audio:
  scan_directories:
    - /mnt/c/Users/Arpit/Music/Vocaloid

  scan_formats:
    - .flac
    - .mp3
    - .ogg
    - .opus
    - .wav
